// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArY-sT2EdUNRkItkveSueFjfjmJHe-3o',
    appId: '1:691016247167:web:2e744d8a6b16d6b18c5c4a',
    messagingSenderId: '691016247167',
    projectId: 'careitshareit-7d100',
    authDomain: 'careitshareit-7d100.firebaseapp.com',
    storageBucket: 'careitshareit-7d100.firebasestorage.app',
    measurementId: 'G-MKKBTSNM6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPcThPkElI4jE3VblYz170u8jYOSh0Wfo',
    appId: '1:691016247167:android:49e0d6203fcbc7458c5c4a',
    messagingSenderId: '691016247167',
    projectId: 'careitshareit-7d100',
    storageBucket: 'careitshareit-7d100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFRHPmCCrR6y8yRvdz2TTm0D9B_cuQ8i8',
    appId: '1:691016247167:ios:7735ab8fce3bd5c48c5c4a',
    messagingSenderId: '691016247167',
    projectId: 'careitshareit-7d100',
    storageBucket: 'careitshareit-7d100.firebasestorage.app',
    iosBundleId: 'com.example.careitShareit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFRHPmCCrR6y8yRvdz2TTm0D9B_cuQ8i8',
    appId: '1:691016247167:ios:7735ab8fce3bd5c48c5c4a',
    messagingSenderId: '691016247167',
    projectId: 'careitshareit-7d100',
    storageBucket: 'careitshareit-7d100.firebasestorage.app',
    iosBundleId: 'com.example.careitShareit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAArY-sT2EdUNRkItkveSueFjfjmJHe-3o',
    appId: '1:691016247167:web:a788c4887b6e27898c5c4a',
    messagingSenderId: '691016247167',
    projectId: 'careitshareit-7d100',
    authDomain: 'careitshareit-7d100.firebaseapp.com',
    storageBucket: 'careitshareit-7d100.firebasestorage.app',
    measurementId: 'G-0SCD8DXL0D',
  );
}
